  #cloud-config
packages:
    - git
    - zsh
    - ntp
    - nano
    - wget
    - curl
    - ansible  # Add ansible here!

users:
  - default
  - name: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel

write_files:
    - content: |
        #!/bin/bash
        cd /home/ansible
        git clone https://github.com/gdepuyt/ansible
        ansible-playbook -c local -i "127.0.0.1," ./ansible/playbook.yaml
      path: /tmp/init-with-ansible.sh
      permissions: 0700

runcmd:
  - 'sudo mv /tmp/init-with-ansible.sh /home/ansible/init-with-ansible.sh'
  - 'sudo chown ansible:ansible /home/ansible/init-with-ansible.sh'
  - 'sudo -u ansible /bin/bash -c "/home/ansible/init-with-ansible.sh > /home/ansible/init-with-ansible.log 2>&1"'