- hosts: 127.0.0.1
  become: true
  tasks:
    - name: Create a directory
      file:
        path: /tmp/my_dir
        state: directory
    - name: Add NodeSource repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_22.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
        filename: nodesource

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        